const dataDoctor = [
  {
    id: "45c4a29f2fb0",
    img: "/img/doctor/doctor.svg",
    str: "1211100318091909",
    sip: "0964/SIP/DPMPTSP/MDN/3.1/II/2022",
    gender: "Laki - laki",
    tipe: "Dokter umum",
    name: "dr. Akbar Jaidi M.K.M",
    education: [
      "S-2 Fakultas Kesehatan Masyarakat   Universitas Sumatera Utara 2016 s/d 2019",
      "Program Studi Profesi Dokter Universitas Islam Sumatera Utara 2005 s/d 2007",
      "S-1 Fakultas Kedokteran Universitas Islam Sumatera Utara 2001 s/d 2005",
    ],
    work_exp: [
      "2007 s/d sekarang; Melakukan praktik Kedokteran Umum di Klinik Spesialis Bunda Medan sebagai Dokter Poliklinik Umum",
      "2007 s/d 2020; Melakukan praktik Kedokteran Umum di Klinik Kimia Farma Medan sebagai Dokter Medical Check-Up",
      "2007 s/d sekarang; Mengajar di Fakultas Kedokteran Universitas Islam Sumatera Utara Departemen Mikrobiologi",
      "2021 s/d sekarang; Sekretaris unit Uji Kompetensi Mahasiswa Pendidikan Profesi Dokter di Fakultas Kedokteran Universitas Islam Sumatera Utara, adapun capaian yang pernah diraih bersama tim adalah angka kelulusan mahasiswa mencapai 75%",
      "2016 s/d 2020; Melakukan praktik Kedokteran Umum di RS Permata Bunda Medan sebagai Dokter Jaga UGD",
      "2016 s/d 2017; Memegang jabatan struktural sebagai Kepala Bidang Pelayanan Medis di RS Permata Bunda Medan",
      "2017 s/d 2018; Memegang jabatan struktural sebagai Wakil Direktur Umum di RS Permata Bunda Medan, adapun pencapaian yang pernah saya lakukan antara lain RS Permata Bunda berhasil keluar dari kategori hitam untuk dampak lingkungan hidup",
      "2018 s/d sekarang; Memegang jabatan struktural sebagai Wakil Direktur Medis di RS Permata Bunda Medan dan ketua tim akreditasi, dimana hasil yang dicapai bersama tim adalah RS Permata Bunda telah mendapatkan akreditasi bintang 2, capaian lainnya adalah menjadi ketua tim untuk membantu didalam menyiapkan kelengkapan berkas dan ketepatan waktu pengklaiman BPJS dan sampai saat ini telah dibayarkan seluruhnya oleh pihak BPJS ke RS Permata Bunda ",
      "2018 s/d sekarang; Ketua tim khitanan massal Bank Mandiri sebagai bukti bakti sosial dan dakwah terhadap masyarakat di daerah Medan dan sekitarnya",
      "2019 s/d sekarang; Mengajar sebagai dosen luar biasa di Fakultas Ilmu Kesehatan Universitas Sumatera Utara jurusan S-1 Administrasi Kebijakan Kesehatan",
      "2021 s/d sekarang; Ketua tim vaksinator CT Corp, capaian target peserta vaksin 850-1000 orang per hari, minim kendala teknis di lapangan pada minggu pertama pelaksanaan vaksin dan sampai saat ini kendala dapat teratasi dan pelaksanaan vaksinasi bersama tim dapat berjalan dengan lancar ",
    ],
  },
  {
    id: "23832c2c1c33",
    img: "/img/doctor/doctor.svg",
    str: "",
    sip: "",
    gender: "Laki - laki",
    tipe: "Dokter umum",
    name: "dr. Farhan Kelvin",
    education: [
      "Fakultas Kedokteran Universitas Islam Sumatera Utara 2010-2018",
    ],
    work_exp: [
      "RSU Mitra Medika Premiere Januari 2021 - Sekarang  (Bekerja Sebagai Dokter Umum )",
      "Vaksin Bersama Ct Corp Oktober 2021 - Desmeber 2021 (Bekerja Sebagai Dokter Vaksinator )",
      "Sentra Vaksinasi Bumn Juni 2021 - Agustus 2021 (Bekerja Sebagai Dokter Vaksinator )",
      "RSIA Karya Jaya Medan Agustus 2020 - Sekarang  (Bekerja Sebagai Doker Igd Dan Dokter Poli Umum)",
      "RSU Permata Bunda Medan April 2020 - Juni 2021 (Bekerja Sebagai Doker Igd Dan Dokter Dan Case Menager )",
      "RSU Bahagia Medan Desmber 2019 - Agustus 2020 (Bekerja Sebagai Doker Igd Dan Dokter Poli Umum)",
      "Kinik Riski Desmber 2019 - Desmber 2020 (Bekerja Sebagai Dokter Umum Di Klinik Tersebut )",
      "Puskesmas Kota Blangkejeren Internship Agustus 2019 - Nopember 2019 (Bekerja Sebagai Dokter Internship Kemenkes Ri)",
      "RSUD Gayo Lues Iternship Nopember 2018 - Agustus 2019 (Bekerja Sebagai Dokter Internship Kemkes Ri)",
      "Klinik Ananda Sei Mecirim Juli 2017-Januari 2018 (Bekerja Sebagai Dokter Poli Umum ) ",
      "Klinik Idosehat 2000 Jakarta Selatan Maret 2017- Juli 2017 (Bekerja Sebagai Doker Igd Dan Dokter Poli Umum)",
      "RSU Wulan Windi Marelan Agustus 2016- Maret  2017 (Bekerja Sebagai Dokter Igd Di Rsu Tersebut)",
      "Klinik Citra Medika 1 & 2 Agustus 2016 - Maret 2017 (Bekerja Sebagai Dokter Umum di Klinik Tersebut)",
    ],
  },
  {
    id: "441888a8b1c7",
    img: "/img/doctor/doctor.svg",
    str: "",
    sip: "",
    gender: "Laki - laki",
    name: "dr. Hadiguna Ahmad",
    tipe: "Dokter umum",
    education: [
      "S-2 Fakultas Kesehatan Masyarakat Universitas Sumatera Utara 2016-2019",
      "S-1 Fakultas Kedokteran Universitas Islam Sumatera Utara 2010-2016",
    ],
    work_exp: [
      "Penanggung Jawab K-3 Klinik Kimia Farma medan 2019-Sekarang",
      "Ka.Bid Pelayanan Medis di RS.Permata Bunda 2019-2021",
      "Tim Pengajar Bimbingan UKMPPD FK-UISU 2019-Sekarang",
      "Dokter praktik di Klinik Kimia Farma Medan 2018-Sekarang",
      "Dokter praktik di Klinik Spesialis Bunda 2018-2021",
    ],
  },

  {
    id: "18bd62dc75a1",
    img: "/img/doctor/doctor.svg",
    str: "",
    sip: "",
    gender: "Laki - laki",
    tipe: "Dokter umum",
    name: "dr. Yusuf Muhumbar M.K.M",
    education: [
      "FAKULTAS KEDOKTERAN UNIVERSITAS ISLAM SUMATERA UTARA 2012 - 2019"
    ],
    work_exp: [
      "RSUD KAYU AGUNG MEI - OKTOBER 2020 (Dokter Jaga /Dokter Intersip)",
      "PUSKESMAS TUGU MULYO NOVEMBER - FEB 2021 (Dokter Jaga /Dokter Intersip)",
      "KLINIK LIANDA MARET - MEI 2021 (Dokter Klinik)",
      "KLINIK KASIH IBU APRIL 2021 - SEKARANG (Dokter Klinik)",
      "RSU PERMATA BUNDA MEDAN APRIL - JUNI 2021 (Dokter jaga IGD)",
      "VAKSINATOR SENTRA VAKSINASI BERSAMA BUMN JUNI - JULI 2021 (SVB BUMN) EKS BANDARA POLONIA",
    ],
  },
];

export default dataDoctor;