variables:
  RELEASE: "false"
  RELEASE_PROD: "false"

stages:
  - test
  - build-dev
  - build-prod

test:
  stage: test
  only:
    variables:
      - $RELEASE == "false" && $RELEASE_PROD == "false"
  before_script:
    - apk add make docker-compose
    - docker system prune -f -a
    - docker image prune -f -a
  script:
    - make TAG=cdi/build/frontend:test CI_PIPELINE_ID=$CI_PIPELINE_ID BUILD_TYPE=dev build
    - make test

build-dev:
  stage: build-dev
  except:
    - tags
  before_script:
    - mkdir -p ~/.ssh || true
    - eval `ssh-agent -s`
    - ssh-add <(echo "$AUTOMATION_PRIVATE_KEY")
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    
    - docker system prune -f -a
    - docker image prune -f -a
    - apk add make git
    - cat registry.json | docker login -u _json_key --password-stdin https://asia.gcr.io
  script:
    - export TAGID=prod-$(date "+%Y%m%d")-$CI_PIPELINE_ID
    - export TAG=asia.gcr.io/castellum-digital-indonesia/jd-doctor:$TAGID
    - make TAG=$TAG CI_PIPELINE_ID=$CI_PIPELINE_ID BUILD_TYPE=dev build
    - docker push $TAG

    # Let's do a magic update for app
    - ssh fhir@castellumdigital.org "(cd demo/jumpadokter && sed -i -r 's/JD_DOCTOR\=(.+)/JD_DOCTOR='"$TAGID"'/g' .env && chmod +x doctor && ./doctor )"
  only:
    - develop

build-prod:
  stage: build-prod
  except:
    - tags
  only:
    - main
  before_script:
    - mkdir -p ~/.ssh || true
    - eval `ssh-agent -s`
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    
    - docker system prune -f -a
    - docker image prune -f -a
    - apk add make git
    - cat registry.json | docker login -u _json_key --password-stdin https://asia.gcr.io
  script:
    - export TAGID=prod-$(date "+%Y%m%d")-$CI_PIPELINE_ID
    - export TAG=asia.gcr.io/castellum-digital-indonesia/jd-doctor:$TAGID
    - make TAG=$TAG CI_PIPELINE_ID=$CI_PIPELINE_ID BUILD_TYPE=prod build
    - docker push $TAG

    # Let's do a magic update for app
    - ssh jumpadokter@jumpadokter.com "(cd doctor && sed -i -r 's/JD_DOCTOR\=(.+)/JD_DOCTOR='"$TAGID"'/g' .env && chmod +x run && ./run)"
